import type { Metadata } from "next";
import { ebGaramond, helveticaNeue } from "./ui/fonts/fonts";
import "./globals.css";
import Nav from "./ui/nav";
import Toolbar from "./ui/toolbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.variable} ${helveticaNeue} antialiased`}
      >
        <Nav />
        {children}
        <Toolbar />
      </body>
    </html>
  );
}
